<a href="https://colab.research.google.com/github/JESUSLONDONO-byte/MetNumUN2022II/blob/main/Lab2/inicial_jelondonoo_ScottsSanderson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install -U fortran-magic

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.6 MB 4.7 MB/s 


In [6]:
%reload_ext fortranmagic

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [7]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [8]:
assert ran_the_first_cell, "Oh noes!"

In [9]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

**My own example 1**

In [10]:
a = [2, 'viar', 6.0, 8, "zehn", "zwölf"]
a

[2, 'viar', 6.0, 8, 'zehn', 'zwölf']

In [11]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


**My own example 2**

In [12]:
primero = a[1]
segundo = a[3]
print("primero:", primero)
print("segundo:", segundo)

primero: viar
segundo: 8


In [13]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


**My owne example 3**

In [14]:
ultimo = l[-1]
penultimo = l[-2]
print("ultimo:", ultimo)
print("penultimo:", penultimo)

ultimo: six
penultimo: 5.0


In [15]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

**My own example 4**

In [16]:
sublist = a[0:4]
sublist

[2, 'viar', 6.0, 8]

In [17]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

**My own example 5**

In [18]:
primero2 = a[:2]
primero2

[2, 'viar']

In [19]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

**My own example 6**

In [20]:
luego4 = a[4:]
luego4

['zehn', 'zwölf']

In [21]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

**My own example 7**

In [22]:
a = ['eins', 'zwei', 'drei', 'viar', 'fünf', 'sechs', 'acht','nein']
a[3:7:4]



['viar']

In [23]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

**My own example 8**

In [24]:
a[::-2]

['nein', 'sechs', 'viar', 'zwei']

In [25]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


**My own example 9**

In [26]:
a = [2, 4, 6, 8, 10]
print("Antes:", a)
a.append('Doce')
print("Después:", a)

Antes: [2, 4, 6, 8, 10]
Después: [2, 4, 6, 8, 10, 'Doce']


In [27]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

**My own example 10**

In [28]:
a = [2, 4, 6, 8, 10]
[x * 8 for x in a]

[16, 32, 48, 64, 80]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [29]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

**My own example 11**

In [30]:
countrys = {'Deuschland': 'Österreich', 'Chile': 'China', 'Usa': 'Frankreich'}
countrys

{'Deuschland': 'Österreich', 'Chile': 'China', 'Usa': 'Frankreich'}

In [31]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

**My own example 12**

In [32]:
countrys['Chile'] = 'Argentina'
countrys

{'Deuschland': 'Österreich', 'Chile': 'Argentina', 'Usa': 'Frankreich'}

In [33]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [34]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

**My own example 13**

In [35]:
m = [[4, 5, 6],
     [3, 6, 11],
     [2, 7, 10],
     [1, 8, 9]]

n = [[2, 4, 6, 8],
     [3, 6, 9, 12]]

In [36]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 14**

In [37]:
def matmul(M, N):
    """Multiply matrix M by matrix N."""
    c = len(M)
    d = len(N[0])
    out = [[0 for col in range(d)] for row in range(c)]
    
    for i in range(c):
        for j in range(d):
            for k in range(len(N)):
                out[i][j] += M[i][k] * N[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [38]:
%%time

matmul(a, b)

CPU times: user 38 µs, sys: 6 µs, total: 44 µs
Wall time: 50.5 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 15**

In [39]:
%%time

matmul(m, n)

CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 47.2 µs


[[23, 46, 69, 92], [24, 48, 72, 96], [25, 50, 75, 100], [26, 52, 78, 104]]

In [40]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.1459748389594755, 0.7307038948824056, 0.8712528640890634],
 [0.03641624024475976, 0.6855542276247979, 0.18241702133679916]]

**My own example 16**

In [41]:
import random
def random_matrix(a, b):
    out = []
    for row in range(a):
        out.append([random.random() for _ in range(b)])
    return out

randm = random_matrix(2, 3)
randm

[[0.30583454768909646, 0.4590824928257313, 0.9035131178453273],
 [0.028878245427366944, 0.20811175054242992, 0.031064597140975203]]

In [42]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 9.96 s, sys: 41.9 ms, total: 10 s
Wall time: 11.1 s


**My own example 17**

In [43]:
%%time
Ronda = random_matrix(345, 21)
Rondb = random_matrix(21, 345)
x = matmul(Ronda, Rondb)

CPU times: user 995 ms, sys: 9.69 ms, total: 1 s
Wall time: 1.23 s


In [44]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

**My own example 18**

In [45]:
def python_dot_product(x1, y1):
    return sum(x * y for x, y in zip(x1, y1))

In [46]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

**My own example 19**

In [47]:
%%fortran
subroutine fortran_dot_product(x1, y1, result)
    double precision, intent(in) :: x1(:)
    double precision, intent(in) :: y1(:)
    double precision, intent(out) :: result
     result = sum(x1 * y1)
end

In [48]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [49]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 16.5 ms, sys: 0 ns, total: 16.5 ms
Wall time: 17.1 ms


333328333350000.0

**My own example 20**

In [50]:
c = [float(i) for i in range(3000)]
datos = np.array(c)


**My own example 21**

In [51]:
%%time
python_dot_product(c, c)

CPU times: user 465 µs, sys: 36 µs, total: 501 µs
Wall time: 510 µs


8995500500.0

In [52]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 200 µs, sys: 0 ns, total: 200 µs
Wall time: 208 µs


333328333350000.0

**My own example 22**

In [53]:
%%time
fortran_dot_product(datos, datos)

CPU times: user 18 µs, sys: 0 ns, total: 18 µs
Wall time: 22.6 µs


8995500500.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [54]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

**My own example 23**

In [55]:
def mul_elemwise(x1, y1):
    return [x * y for x, y in zip(x1, y1)]

mul_elemwise([2, 4, 6, 8], [3, 6 + 0j, 9.0, 'zwei'])
#[type(x) for x in _]

[6, (24+0j), 54.0, 'zweizweizweizweizweizweizweizwei']

In [56]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


**My own example 24**

In [57]:
codigo = 'c + d * a'
byte = compile(codigo, '', 'eval')
import dis; dis.dis(byte)

  1           0 LOAD_NAME                0 (c)
              2 LOAD_NAME                1 (d)
              4 LOAD_NAME                2 (a)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [58]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

**My own example 25**

In [59]:
datos = np.array([2, 4, 6, 8])
datos

array([2, 4, 6, 8])

In [60]:
data + data

array([2, 4, 6, 8])

**My own example 26**

In [61]:
datos + datos


array([ 4,  8, 12, 16])

In [62]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 107 µs, sys: 1.02 ms, total: 1.13 ms
Wall time: 3.15 ms


333328333350000.0

**My own example 27**

In [63]:
%%time
# Naive dot product
(datos * datos).sum()

CPU times: user 86 µs, sys: 0 ns, total: 86 µs
Wall time: 93.7 µs


120

In [64]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 5.51 ms, sys: 1.9 ms, total: 7.41 ms
Wall time: 9.7 ms


333328333350000.0

**My own example 28**

In [65]:
%%time
# Built-in dot product.
datos.dot(datos)

CPU times: user 32 µs, sys: 2 µs, total: 34 µs
Wall time: 39.3 µs


120

In [66]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 157 µs, sys: 12 µs, total: 169 µs
Wall time: 175 µs


333328333350000.0

**My own example 29**

In [67]:
%%time
fortran_dot_product(datos, datos)

CPU times: user 69 µs, sys: 5 µs, total: 74 µs
Wall time: 56.7 µs


120.0

In [68]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


**My own example 30**

In [70]:
A = np.array([2, 4, 6, 8, 10, 12], dtype='int16').reshape(2, 3)
print("Array:\n", A, sep='')
print("===========")
print("DType:", A.dtype)
print("Shape:", A.shape)
print("Strides:", A.strides)
print("Data:", A.data.tobytes())

Array:
[[ 2  4  6]
 [ 8 10 12]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x02\x00\x04\x00\x06\x00\x08\x00\n\x00\x0c\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [71]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**My own example 31**

In [72]:
datos = np.arange(20).reshape(4, 5)
datos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

**My own example 32**

In [74]:
datos*datos

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [75]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

**My own example 33**

In [76]:
np.sqrt(datos)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [77]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

**My own example 34**

In [78]:
(datos % 4) == 0

array([[ True, False, False, False,  True],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False]])

In [79]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

**My own example 35**

In [80]:
((datos % 5) == 0) & ((datos % 7) == 0)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [81]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

**My own example 36**

In [82]:
datos @ datos.T

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [83]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 37**

In [84]:
seno = np.sin(np.linspace(0, 3.14, 13))
coseno = np.cos(np.linspace(0, 3.14, 13))
seno

array([0.        , 0.25869084, 0.4997701 , 0.70682518, 0.86575984,
       0.96575386, 0.99999968, 0.96616586, 0.8665558 , 0.70795091,
       0.50114896, 0.26022896, 0.00159265])

In [85]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

**My own example 38**

In [86]:
coseno[0]

1.0

In [87]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

**My own example 39**

In [88]:
seno[:1]

array([0.])

In [89]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 40**

In [90]:
coseno[2:]

array([ 8.66158094e-01,  7.07388269e-01,  5.00459689e-01,  2.59459982e-01,
        7.96326711e-04, -2.57921542e-01, -4.99080199e-01, -7.06261645e-01,
       -8.65361036e-01, -9.65546939e-01, -9.99998732e-01])

In [91]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

**My own example 41**

In [92]:
seno[::3]

array([0.        , 0.70682518, 0.99999968, 0.70795091, 0.00159265])

In [93]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


**My own example 42**

In [94]:
print("seno:\n", seno)
print("seno > 0.3:\n", seno > 0.3)
print("seno[seno > 0.5]:\n", seno[seno > 0.3])

seno:
 [0.         0.25869084 0.4997701  0.70682518 0.86575984 0.96575386
 0.99999968 0.96616586 0.8665558  0.70795091 0.50114896 0.26022896
 0.00159265]
seno > 0.3:
 [False False  True  True  True  True  True  True  True  True  True False
 False]
seno[seno > 0.5]:
 [0.4997701  0.70682518 0.86575984 0.96575386 0.99999968 0.96616586
 0.8665558  0.70795091 0.50114896]


In [95]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

**My own example 43**

In [96]:
print(seno)
sines[[2, 5, 9]]

[0.         0.25869084 0.4997701  0.70682518 0.86575984 0.96575386
 0.99999968 0.96616586 0.8665558  0.70795091 0.50114896 0.26022896
 0.00159265]


array([0.64251645, 0.98496101, 0.00159265])

In [97]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

**My own example 44**

In [98]:
datos = np.array([2, 3, 5, -7, -11, 13, -17])

In [99]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

**My own example 45**

In [100]:
s = np.argsort(datos)
s

array([6, 4, 3, 0, 1, 2, 5])

In [101]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

**My own example 46**

In [102]:
datos[s]

array([-17, -11,  -7,   2,   3,   5,  13])

In [103]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

**My own example 47**

In [104]:
m = np.array([24, 36, 17, 21, 61]) 

In [105]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

**My own example 48**

In [106]:
sm = np.argsort(m)
assets[sm]

array(['C', 'D', 'A', 'B', 'E'], dtype='<U1')

In [107]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [108]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [109]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**My own example 49**

In [110]:
datos = np.arange(30).reshape(5, 6)
datos

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [111]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

**My own example 50**

In [112]:
datos[:1, :3]

array([[0, 1, 2]])

In [113]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

**My own example 51**

In [114]:
datos[:3, [1, -2]]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [115]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

**My own example 52**

In [116]:
datos[(datos[:, 3] % 6) == 0]

array([], shape=(0, 6), dtype=int64)

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [117]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [118]:
variance(np.random.standard_normal(1000))

0.9915437288281649

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [119]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [120]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [121]:
data.mean()

14.5

In [122]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [123]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [124]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


**My own example 53**

In [125]:
r = np.array([2, 4, 6, 8])
columna = np.array([[1], [2], [3]])
print("R:\n", r, sep='')
print("Columna:\n", columna, sep='')

R:
[2 4 6 8]
Columna:
[[1]
 [2]
 [3]]


In [126]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

**My own example 54**

In [127]:
r+columna

array([[ 3,  5,  7,  9],
       [ 4,  6,  8, 10],
       [ 5,  7,  9, 11]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [128]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


**My own example 55**

In [129]:
print("Datos:\n", datos, sep='')
print("Media:\n", datos.mean(axis=0), sep='')
print("Datos - Media:\n", datos - datos.mean(axis=0), sep='')

Datos:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Media:
[12. 13. 14. 15. 16. 17.]
Datos - Media:
[[-12. -12. -12. -12. -12. -12.]
 [ -6.  -6.  -6.  -6.  -6.  -6.]
 [  0.   0.   0.   0.   0.   0.]
 [  6.   6.   6.   6.   6.   6.]
 [ 12.  12.  12.  12.  12.  12.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [130]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

**My own example 56**

In [131]:
z = pd.Series(index=['eins', 'zwei', 'drei', 'viar', 'fünf'], data=[3, 6, 9, 12, 15])
z

eins     3
zwei     6
drei     9
viar    12
fünf    15
dtype: int64

In [132]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


**My own example 57**

In [133]:
print("The index is:", z.index)
print("Los valores son:", z.values)

The index is: Index(['eins', 'zwei', 'drei', 'viar', 'fünf'], dtype='object')
Los valores son: [ 3  6  9 12 15]


In [134]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [135]:
# ... or by label.
s.loc['a']

1

In [136]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [137]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [138]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [139]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [140]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

**My own example 58**

In [141]:
otraz = pd.Series({'zwanzig': 31.0, 'dreissig': 42.0, 'nuenzig': 21.0, 'achtzehn': 97.0})
otraz

zwanzig     31.0
dreissig    42.0
nuenzig     21.0
achtzehn    97.0
dtype: float64

In [142]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [143]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [144]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [145]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [146]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

NameError: ignored

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!